version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - ./infra/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: validacaoPesquisaDjango
      MYSQL_USER: validacao
      MYSQL_PASSWORD: validacao
    ports:
      - "3306:3306"

volumes:
  db_data: {}

